# Generated by Django 3.0.3 on 2020-02-22 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons_card', '0003_auto_20200222_1904'),
        ('device_message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device_message',
            old_name='time',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='device_message',
            old_name='reader_id',
            new_name='readerID',
        ),
        migrations.RemoveField(
            model_name='device_message',
            name='name',
        ),
        migrations.AddField(
            model_name='device_message',
            name='persons_card',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='persons_card.Persons_Card'),
            preserve_default=False,
        ),
    ]
