# Generated by Django 3.0.3 on 2020-02-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_message', '0002_auto_20200222_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device_message',
            name='date_time',
        ),
        migrations.AddField(
            model_name='device_message',
            name='date_f',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device_message',
            name='time_f',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
    ]
