# Generated by Django 3.0.3 on 2020-02-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_message', '0003_auto_20200222_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_message',
            name='readerID',
            field=models.TextField(),
        ),
    ]
