# Generated by Django 3.0.3 on 2020-02-22 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('departaments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departaments.Departaments')),
            ],
        ),
    ]
