# Generated by Django 3.0.3 on 2020-02-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persons_Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
        ),
    ]
