# Generated by Django 3.0.3 on 2020-02-22 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20200222_1725'),
        ('persons_card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons_card',
            name='persons',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='persons.Persons'),
            preserve_default=False,
        ),
    ]
