# Generated by Django 3.0.3 on 2020-02-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons_card', '0002_persons_card_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons_card',
            name='active',
            field=models.IntegerField(),
        ),
    ]
