# Generated by Django 3.0.3 on 2020-02-22 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departaments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('organizations', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Organizations')),
            ],
        ),
    ]
