# Generated by Django 3.0.3 on 2020-02-22 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('departaments', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='departaments',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='departaments.Departaments'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persons',
            name='jobs',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='jobs.Jobs'),
            preserve_default=False,
        ),
    ]
